name: Setup Qt
description: Setups Qt
outputs:
  qt-path:
    description: Qt path
    value: ${{ steps.main.outputs.qt-path }}
  qt-bin-path:
    description: Qt bin path
    value: ${{ steps.main.outputs.qt-bin-path }}
runs:
  using: composite
  steps:
  - run: |
      rem curl -L -o Qt-5.15.2-mingw64.zip https://github.com/mugiseyebrows/hey-action/releases/download/v14/Qt-5.15.2-mingw64.zip
      rem 7z x Qt-5.15.2-mingw64.zip
      echo ::set-output name=qt-path::%CD%\Qt-5.15.2-mingw64
      echo ::set-output name=qt-bin-path::%CD%\Qt-5.15.2-mingw64\bin
    shell: cmd
    id: main