name: Setup Qt
description: Setups Qt
outputs:
  path:
    description: Qt path
    value: ${{ steps.main.outputs.path }}
  bin-path:
    description: Qt bin path
    value: ${{ steps.main.outputs.bin-path }}
runs:
  using: composite
  steps:
  - run: |
      curl -L -o Qt-5.15.2-mingw64.zip https://github.com/mugiseyebrows/hey-action/releases/download/v14/Qt-5.15.2-mingw64.zip
      7z x Qt-5.15.2-mingw64.zip
      echo ::set-output name=path::%CD%\Qt-5.15.2-mingw64
      echo ::set-output name=bin-path::%CD%\Qt-5.15.2-mingw64\bin
      echo QT_BIN_PATH=%CD%\Qt-5.15.2-mingw64\bin>> %GITHUB_ENV%
      echo QT_VERSION=5.15.2>> %GITHUB_ENV%
    shell: cmd
    id: main