name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - run: |
          set PATH=C:\Program Files\PostgreSQL\14\bin;C:\mysql\bin;%PATH%
          mysql.exe --version
          psql.exe --version
        shell: cmd
      - run: C:\msys64\usr\bin\file.exe "C:\Program Files\PostgreSQL\14\bin\libpq.dll"
      - run: C:\msys64\usr\bin\file.exe C:\mysql\bin\mysql.exe
        
