name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set PATH=C:\Miniconda;%PATH%
          python -m pip install aqtinstall
          python -m aqt install 5.15.2 windows desktop win64_mingw81 -O Qt
          echo %CD%
          python list.py .
        shell: cmd
