name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: ./.github/actions/setup-qt
        name: setup-qt

      - uses: ./.github/actions/setup-mingw
        name: setup-mingw

      - uses: ./.github/actions/setup-mugideploy
        name: setup-mugideploy

      - run: |
          set PATH=%QT_BIN_PATH%;%MINGW_BIN_PATH%;%PATH%
          qmake
          mingw32-make release
          %MUGIDEPLOY_PATH% collect --app app --version 1.0.0 --bin release\app.exe
          7z a app-1.0.0-win64.zip app-1.0.0-win64
        shell: cmd
        name: build

      - uses: softprops/action-gh-release@v1
        with:
          files: app-1.0.0-win64.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release