name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: ./.github/actions/foo
      - run: python list.py
        shell: cmd
      - uses: actions/upload-artifact@v3
        with:
          path: list.txt

