name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - run: |
          curl -L -o "Qt-5.15.2-mingw64.zip" https://github.com/mugiseyebrows/hey-action/releases/download/v14/Qt-5.15.2-mingw64.zip
          dir
        shell: cmd
        name: build qt
