name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -c "import sys;import os;print(os.getcwd());print(sys.modules['site'])"
        shell: cmd
      - run: python -m pip install -r requirements.txt
        shell: cmd
      - run: python -c "import sys;import aqt;import os;print(os.getcwd());print(sys.modules['aqt'])"
        shell: cmd
      