name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - run: curl --help
        shell: cmd
        name: build qt
