name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        with:
          path: "qtbase-everywhere-src-5.15.2/**/*.o"
          key: build-cache
        name: build cache

      - run: |
          set PATH=C:\Miniconda\python;C:\Miniconda\Scripts;%PATH%
          pip install mugicli
          pyfind qtbase-everywhere-src-5.15.2 -iname *.o -exec pytouch -d 1d {} ;
        shell: cmd
        name: touch objects

      - run: where API-MS-WIN-CRT-HEAP-L1-1-0.DLL
        shell: cmd

      - run: echo skip
        shell: cmd
        name: build qt

      - uses: softprops/action-gh-release@v1
        with:
          files: Qt-5.15.2-mingw64.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release