name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        id: cache-objects
        with:
          path: "qtbase-everywhere-src-5.15.2/**/*.o"
          key: build-cache-3
        name: build cache

      - run: |
          set PATH=C:\Miniconda\python;C:\Miniconda\Scripts;%PATH%
          pip install mugicli
          pyfind qtbase-everywhere-src-5.15.2 -iname *.o -exec pytouch -d 1d {} ;
        shell: cmd
        if: steps.cache-objects.outputs.cache-hit == 'true'
        name: touch objects

      - run: build.bat
        shell: cmd
        name: build qt

      - run: |
          set PATH=C:\Miniconda\python;C:\Miniconda\Scripts;%PATH%
          pip install mugideploy
          mugideploy collect --bin Qt-5.15.2-mingw64\plugins\sqldrivers\qsqlpsql.dll --no-vcredist
          del qsqlpsql-0.0.1-win64\Qt5Core.dll
          del qsqlpsql-0.0.1-win64\Qt5Sql.dll
          del qsqlpsql-0.0.1-win64\qt.conf
          move qsqlpsql-0.0.1-win64 qsqlpsql-win64
          7z a -y "qsqlpsql-win64.zip" "qsqlpsql-win64"
          mugideploy collect --bin Qt-5.15.2-mingw64\plugins\sqldrivers\qsqlmysql.dll --no-vcredist
          del qsqlmysql-0.0.1-win64\Qt5Core.dll
          del qsqlmysql-0.0.1-win64\Qt5Sql.dll
          del qsqlmysql-0.0.1-win64\qt.conf
          move qsqlmysql-0.0.1-win64 qsqlmysql-win64
          7z a -y "qsqlmysql-win64.zip" "qsqlmysql-win64"
        shell: cmd
        name: qsqlpsql qsqlmysql deps

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            Qt-5.15.2-mingw64.zip
            qsqlpsql-win64.zip
            qsqlmysql-win64.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release