name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        with:
          path: "**/*.o"
          key: build-cache
        name: build cache

      - run: |
          set PATH=C:\Miniconda\python;C:\Miniconda\Scripts;%PATH%
          pip install mugicli
          pyfind -iname *.o -exec pytouch -d 1d {} ;
        shell: cmd
        name: touch objects

      - run: |
          xcopy /e /i "C:\Program Files\PostgreSQL\14\bin" pgbin > NUL
          xcopy /e /i "C:\Program Files\PostgreSQL\14\include" pginclude > NUL
          if not exist "pgbin.zip" 7z a -y "pgbin.zip" "pgbin"
          if not exist "pginclude.zip" 7z a -y "pginclude.zip" "pginclude"
        shell: cmd

      - run: echo skip
        shell: cmd
        name: build qt

      - uses: actions/upload-artifact@v3
        with:
          path: |
            pgbin.zip
            pginclude.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: Qt-5.15.2-mingw64.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release