name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: C:\Miniconda\condabin\conda.bat init powershell
      - run: C:\Miniconda\condabin\conda.bat create -n aqtenv
      - run: C:\Miniconda\condabin\conda.bat env update --file ./.github/workflows/environment.yml --name aqtenv
