name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/foo
      - run: echo hello
        shell: cmd
