name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/cache@v2
        with:
          path: "qtbase-everywhere-src-5.15.2/**/*.o"
          key: build-cache-3
        name: build cache

      - run: build.bat
        shell: cmd
        name: build qt

      - uses: actions/upload-artifact@v3
        with:
          path: postgresql-14.zip

      - uses: softprops/action-gh-release@v1
        with:
          files: Qt-5.15.2-mingw64.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release