name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install virtualenv
        shell: cmd
      - run: python -m venv env1
        shell: cmd
      - run: env1\Scripts\activate
        shell: cmd
      - run: pip install aqtinstall
        shell: cmd
      - run: pip freeze > requirements.txt
        shell: cmd
      - run: python list.py -o list-pythonLocation.txt %pythonLocation%
      - uses: actions/upload-artifact@v3
        with:
          path: |
            "**/requirements.txt"
            list-pythonLocation.txt