name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: C:\Miniconda\python -m pip install aqtinstall mugicli
      - run: C:\Miniconda\python -m mugicli.pyfind C:\Miniconda\Lib\site-packages -maxdepth 1 -type d -mmin -5 > modified-packages.txt
      - run: Get-Content modified-packages.txt
      - uses: actions/upload-artifact@v3
        with:
          path: modified-packages.txt
