name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install aqtinstall
        shell: cmd
      - run: pip freeze > requirements.txt
        shell: cmd
      - uses: actions/upload-artifact@v3
        with:
          path: requirements.txt