name: main
on: push
env:
  MSYSTEM: MINGW32
  CHERE_INVOKING: 'yes'
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: echo this is main
    - name: second
      shell: C:\msys64\usr\bin\bash.exe {0}
      run: |
        echo this is second
        echo CHERE_INVOKING=$CHERE_INVOKING MSYSTEM=$MSYSTEM
        pwd
