name: main
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      
    - name: main
      run: |
        sudo sed -i "s,# deb-src,deb-src," /etc/apt/sources.list
        sudo apt update
        sudo apt install zip
        mkdir samples
        mkdir tmp
        cd tmp
        bash ../find-samples.sh
        cd ..
        zip -r samples.zip samples
          
    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: samples
        path: |
          samples.zip
          samples.txt

    - name: release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: |
          samples.zip
          samples.txt
        token: ${{ secrets.GITHUB_TOKEN }}
