name: main
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - run: |
        sed -i "s,# deb-src,deb-src," /etc/apt/sources.list
        apt update
        apt install zip
        mkdir samples
        mkdir tmp
        cd tmp
        bash ../find-samples.sh
        cd ..
        zip -r samples.zip samples
    
    - uses: actions/upload-artifact@v3
      with:
        name: samples
        path: |
          samples
          samples.txt

    - name: release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: |
          samples.zip
          samples.txt
        token: ${{ secrets.GITHUB_TOKEN }}
