name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
        ninja --version
        cmake --version
        git --version