name: main
on:
  push:
    tags:
      - "test*"
jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: ./.github/actions/setup-qt
        id: setup-qt

      - uses: ./.github/actions/setup-mingw
        id: setup-mingw

      - uses: ./.github/actions/setup-mugideploy
        id: setup-mugideploy
      
      - uses: ./.github/actions/setup-qwt
        id: setup-qwt

      - run: |
          set PATH=${{ steps.setup-qt.outputs.bin-path }};${{ steps.setup-mingw.outputs.bin-path }};${{ steps.setup-qwt.outputs.bin-path }};%PATH%
            pushd test-qwt
            qmake
            mingw32-make release
          popd
          ${{ steps.setup-mugideploy.outputs.mugideploy }} collect --app app --version 1.0.0 --bin test-qwt\release\test-qwt.exe
          7z a app-1.0.0-win64.zip app-1.0.0-win64
          
        shell: cmd

      - uses: softprops/action-gh-release@v1
        with:
          files: app-1.0.0-win64.zip
        if: startsWith(github.ref, 'refs/tags/')
        name: release