name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: set env
      shell: cmd
      run: echo PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\Program Files\7-Zip;C:\windows\system32;C:\windows>> %GITHUB_ENV%
    - name: install mugicli
      shell: cmd
      run: pip install mugicli==0.0.12
    - name: list c
      shell: cmd
      run: pyfind C:\ -maxdepth 3 -output c-listing.txt
    - uses: actions/upload-artifact@v3
      with:
        path: c-listing.txt