name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2019
    steps:
    - run: |
      set PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
      ninja --version
      cmake --version
      shell: cmd