name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: main
      shell: cmd
      run: |
        set test=hello
        echo test=hello>> %GITHUB_ENV%
        echo %test% from cmd
    - name: foo
      shell: python
      run: |
        import os
        print("{} from python".format(os.environ['test']))
    - name: bar
      shell: pwsh
      run: Write-Output "$env:test from powershell"
    - name: baz
      shell: C:\msys64\usr\bin\bash.exe {0}
      run: echo $test from msys2
    - name: qux
      shell: node
      run: console.log(`${process.env.test} from node`)
