name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
      - run: |
          where git
          where 7z
          echo %CD%
        shell: cmd
      - run: echo github.ref ${{ github.ref }}
        shell: cmd
        name: print ref
      - run: echo ${{ github.event.release.tag_name }}
        shell: cmd
        name: print tag_name
