name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: flavour qt5.15.2 mingw8.1.0 x86_64
      shell: cmd
    - run: perl --version
      shell: cmd
    - run: |
        set PATH=%CD%/mysql-8.0.29-winx64/lib;%CD%/mysql-8.0.29-winx64/bin;%CD%\mingw64\bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;%PATH%
        ninja --version
      shell: cmd
      run: |
        set PATH=%CD%\5.15.2\mingw81_64\bin;%CD%\Tools\mingw810_64\bin;C:\Program Files\7-Zip;C:\Miniconda\Scripts;C:\Miniconda;%PATH%
        where aqt || pip install aqtinstall
        if not exist 5.15.2\mingw81_64\bin\qmake.exe aqt install-qt windows desktop 5.15.2 win64_mingw81
        if not exist Tools\mingw810_64\bin\gcc.exe aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810
        if exist release rmdir /q /s release
        del /f .qmake.stash
        del /f Makefile*
        qmake
        mingw32-make
        release\test4.exe
