name: main
on:
  push:
    tags: '*'
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: main
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ninja --version
        cmake --version
        git --version
        git clone --depth 1 https://github.com/llvm/llvm-project.git
        pushd llvm-project\clang\tools
        git clone https://github.com/mugiseyebrows/clang-mute.git
        echo add_clang_subdirectory(clang-mute) >> CMakeLists.txt
        popd
        cd llvm-project
        mkdir build
        cd build
        cmake -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release -G Ninja -D CMAKE_C_COMPILER=cl -D CMAKE_CXX_COMPILER=cl ../llvm
        ninja clang-mute
    - uses: actions/upload-artifact@v3
      with:
        path: llvm-project/build/bin/clang-mute.exe