name: main
on: push
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%
        python -m pip install mugicli
        pyfind -maxdepth 2 C:\ > c.txt
    - uses: actions/upload-artifact@v3
      with:
        name: c.txt
        path: c.txt
    