name: main
on: push
env:
  MSYSTEM: MINGW32
  CHERE_INVOKING: 'yes'
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: test
      shell: python {0}
      run: print(os.listdir("."))
