name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
    - run: cmake --version
      shell: cmd
    - run: perl --version
      shell: cmd
    - run: ninja --version
      shell: cmd