name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    strategy:
      matrix:
        foo:
        - qwe
        - rty
        bar:
        - uio
        - jkl
        include:
        - foo: asd
          bar: fgh
      fail-fast: false
    steps:
    - name: main
      shell: cmd
      run: echo ${{ matrix.foo }} ${{ matrix.bar }}
