name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    strategy:
      matrix:
        foo:
        - qwe
      fail-fast: false
    steps:
    - name: main
      shell: cmd
      run: echo ${{ matrix.foo }}
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump steps context
      run: echo '${{ toJSON(steps) }}'
    - name: Dump runner context
      run: echo '${{ toJSON(runner) }}'
    - name: Dump strategy context
      run: echo '${{ toJSON(strategy) }}'
    - name: Dump matrix context
      run: echo '${{ toJSON(matrix) }}'
