name: main
on: push
jobs:
  main:
    runs-on: windows-2022
    steps:
    - name: main
      shell: pwsh
      run: |
        Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
        install-module pscx -scope CurrentUser -AllowClobber
