name: main
on: push
jobs:
  main:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
        - { msystem: MINGW32, arch: i686}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: git mingw-w64-ucrt-${{ matrix.arch }}-gcc
    - name: test shell
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW32
      run: |
        pwd
        gcc -v
        which gcc
        uname -a
