name: GitHub Actions Demo
on: [push]
jobs:
  main:
    runs-on: windows-2022
    steps:
      - run: |
          where git
          where 7z
          echo %CD%
          echo {{ github.ref }}
        shell: cmd
      - run: echo github.ref {{ github.ref }}
        shell: cmd